resource_group_name         = "terraform_vm_01"
resource_group_location     = "West Europe"
virtual_network_name        = "terraform_vnetprod01"
subnet_name                 = "terraform_subnet01"
public_ip_name              = "terraform_publicip01"
network_security_group_name = "terraform_nsgprod01"
network_interface_name      = "terraform_nicprod01"
linux_virtual_machine_name  = "terraform_linuxvm01"